version: "3.9"
services:
  env:
    build: .
    container_name: env
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - $WORKDIR:/home/roman/w
      - $SSHDIR:/home/roman/.ssh
      - home:/home/roman

volumes:
  home:
